import os

# General
SECRET_KEY = os.getenv("SECRET_KEY")
AWS_REGION = os.getenv("AWS_REGION") or os.getenv("AWS_DEFAULT_REGION")

# AWS Cognito
COGNITO_DOMAIN = os.getenv("COGNITO_DOMAIN")
COGNITO_AUTHORIZATION_URL = f"{COGNITO_DOMAIN}/oauth2/authorize"
COGNITO_TOKEN_URL = f"{COGNITO_DOMAIN}/oauth2/token"
COGNITO_REDIRECT_URI = os.getenv("COGNITO_REDIRECT_URI")
COGNITO_LOGOUT_URI = f"{COGNITO_DOMAIN}/logout"
COGNITO_USER_POOL_ID = os.getenv("COGNITO_USER_POOL_ID")
COGNITO_CLIENT_ID = os.getenv("COGNITO_CLIENT_ID")
COGNITO_AUTHORITY = os.getenv("COGNITO_AUTHORITY")
