services:
  backend:
    build:
      context: ../.. # infra/src directory
      dockerfile: functions/backend/Dockerfile.local
    container_name: uinlp_backend_local
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend/:/var/task/backend
      - ../../scripts/internal/src/internal:/var/task/internal
    env_file:
      - .env.local
