AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: UINLP Backend Service

Resources:
  UinlpBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.10
      CodeUri: .
      MemorySize: 512
      Timeout: 15
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
        Proxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: python3.10

  # UinlpS3Bucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: uinlp-s3-bucket
  #     AccessControl: Private
  #     VersioningConfiguration:
  #       Status: Enabled
  #     LifecycleConfiguration:
  #       Rules:
  #         - Id: DeleteOldVersions
  #           Status: Enabled
  #           NoncurrentVersionExpirationInDays: 30

  # UinlpInternalLayer:
  #   Type: AWS::Lambda::LayerVersion
  #   Properties:
  #     Content:
  #       S3Bucket: uinlp-s3-bucket
  #       S3Key: uinlp-internal-layer.zip
